echo off
color 1
echo Eliminacion de Amenazas y Restauracion de Carpetas Ocultas...
echo PMSys...
echo ...
color 3
echo Mostrando Carpetas ocultas...
Attrib -h -s /d /s
echo ...
color 4
echo Eliminando Amenazas...
del autorun.inf /Q
del *.exe /Q
del *.lnk /Q
del *.svr /Q
rd recycler /s /Q
rd recycled /s /Q
rd restore /s /Q
rd bardaje /s /Q
rd bardage /s /Q
rd found000 /s /Q
echo ...
echo Proceso terminado...